### ISSUE TITLE
Option to make Pretty Beaches work in Creative Mode too

### ISSUE THREAD

**Issue by UnPure** [TwelveIterationMods/PrettyBeaches#15]
Nothing seems to happen when I remove sand in creative mode. Its just the normal flowing water.
Not sure if its required but I made sure that I was in a beach biome while I tried the mod.
In survival mode everything seems to work as intended.

MC: 1.16.1
Forge: 32.0.24
PrettyBeaches: 5.0.0

**Comment by KenyMylankca** [comment]
It's already supposed to not work in creative mode. It's not an issue. It should work in survival mode already.

**Comment by BlayTheNinth** [comment]
An option (default: off) should be added to enable it in Creative Mode too.
